/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const TopicId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TopicData = IDL.Record({ 'id' : TopicId, 'name' : IDL.Text });
export const Answer = IDL.Nat;
export const Attempt = IDL.Record({
  'answers' : IDL.Vec(Answer),
  'user' : IDL.Principal,
  'score' : IDL.Nat,
  'quizId' : QuizId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const QuestionData = IDL.Record({
  'id' : QuestionId,
  'text' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'title' : IDL.Text,
  'questions' : IDL.Vec(QuestionData),
  'topicId' : TopicId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestionToQuiz' : IDL.Func(
      [QuizId, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [QuestionId],
      [],
    ),
  'addTopic' : IDL.Func([IDL.Text], [TopicId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuiz' : IDL.Func([IDL.Text, TopicId], [QuizId], []),
  'getAllTopics' : IDL.Func([], [IDL.Vec(TopicData)], ['query']),
  'getAttemptsByQuiz' : IDL.Func([QuizId], [IDL.Vec(Attempt)], ['query']),
  'getCallerAttemptsByQuiz' : IDL.Func([QuizId], [IDL.Vec(Attempt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuiz' : IDL.Func([QuizId], [IDL.Opt(Quiz)], ['query']),
  'getQuizzesByTopic' : IDL.Func([TopicId], [IDL.Vec(Quiz)], ['query']),
  'getTopic' : IDL.Func([TopicId], [IDL.Opt(TopicData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAttempt' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const TopicId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TopicData = IDL.Record({ 'id' : TopicId, 'name' : IDL.Text });
  const Answer = IDL.Nat;
  const Attempt = IDL.Record({
    'answers' : IDL.Vec(Answer),
    'user' : IDL.Principal,
    'score' : IDL.Nat,
    'quizId' : QuizId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const QuestionData = IDL.Record({
    'id' : QuestionId,
    'text' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'id' : QuizId,
    'title' : IDL.Text,
    'questions' : IDL.Vec(QuestionData),
    'topicId' : TopicId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestionToQuiz' : IDL.Func(
        [QuizId, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [QuestionId],
        [],
      ),
    'addTopic' : IDL.Func([IDL.Text], [TopicId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuiz' : IDL.Func([IDL.Text, TopicId], [QuizId], []),
    'getAllTopics' : IDL.Func([], [IDL.Vec(TopicData)], ['query']),
    'getAttemptsByQuiz' : IDL.Func([QuizId], [IDL.Vec(Attempt)], ['query']),
    'getCallerAttemptsByQuiz' : IDL.Func(
        [QuizId],
        [IDL.Vec(Attempt)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuiz' : IDL.Func([QuizId], [IDL.Opt(Quiz)], ['query']),
    'getQuizzesByTopic' : IDL.Func([TopicId], [IDL.Vec(Quiz)], ['query']),
    'getTopic' : IDL.Func([TopicId], [IDL.Opt(TopicData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAttempt' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };