/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Answer = bigint;
export interface Attempt {
  'answers' : Array<Answer>,
  'user' : Principal,
  'score' : bigint,
  'quizId' : QuizId,
}
export interface QuestionData {
  'id' : QuestionId,
  'text' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export interface Quiz {
  'id' : QuizId,
  'title' : string,
  'questions' : Array<QuestionData>,
  'topicId' : TopicId,
}
export type QuizId = bigint;
export interface TopicData { 'id' : TopicId, 'name' : string }
export type TopicId = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestionToQuiz' : ActorMethod<
    [QuizId, string, Array<string>, bigint],
    QuestionId
  >,
  'addTopic' : ActorMethod<[string], TopicId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuiz' : ActorMethod<[string, TopicId], QuizId>,
  'getAllTopics' : ActorMethod<[], Array<TopicData>>,
  'getAttemptsByQuiz' : ActorMethod<[QuizId], Array<Attempt>>,
  'getCallerAttemptsByQuiz' : ActorMethod<[QuizId], Array<Attempt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuiz' : ActorMethod<[QuizId], [] | [Quiz]>,
  'getQuizzesByTopic' : ActorMethod<[TopicId], Array<Quiz>>,
  'getTopic' : ActorMethod<[TopicId], [] | [TopicData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAttempt' : ActorMethod<[QuizId, Array<bigint>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];